import { Project } from '@/lib/types'

export const projectsData: Project[] = [
  {
    title: 'Artist2Playlist for Spotify',
    description: '一鍵將任何歌手的所有歌曲轉換成播放清單，以解決這個官方沒有提供的功能。',
    imageURL: '/assets/projects/artist-2-playlist.png',
    responsibilities: '前端開發（一人專案）',
    websiteURL: 'https://artist2playlist.yeeway.dev',
    websiteTitle: 'artist2playlist.yeeway.dev',
    githubURL: 'https://github.com/yeeway0609/artist-2-playlist',
    githubTitle: 'artist-2-playlist',
    articleURL: null,
    articleTitle: '文章介紹',
    tags: ['Next.js', 'Spotify API', 'Tailwind CSS'],
  },
  {
    title: '蛇年光雕投影',
    description: '透過光雕投影技術，將建築物轉化為互動式的遊戲場景，讓民眾透過手機即可遊玩巨大版貪食蛇。',
    imageURL: '/assets/projects/year-of-snake.png',
    responsibilities: 'Web App 前端開發',
    websiteURL: null,
    websiteTitle: null,
    githubURL: null,
    githubTitle: null,
    articleURL: 'https://www.boring-lab.com/work/intertrend',
    articleTitle: '文章介紹',
    tags: ['BORING Design', 'React', 'Game'],
  },
  {
    title: '台新銀行 2024 金融科技展',
    description: '四大家族的召喚: 運用生成式 AI 技術打造 MBTI 心理測驗 Web App，具備即時題目生成功能。',
    imageURL: '/assets/projects/tsib-fintech.png',
    responsibilities: 'Web App 前後端開發',
    websiteURL: null,
    websiteTitle: null,
    githubURL: null,
    githubTitle: null,
    articleURL: 'https://www.boring-lab.com/work/tai-xin-yin-xing-2024jin-rong',
    articleTitle: '文章介紹',
    tags: ['BORING Design', 'React', 'Firebase', 'GenAI', 'Three.js ', 'Animation'],
  },
  {
    title: 'Architecture For Dog 官方網站',
    description: 'AFD 計畫為日本設計大師 原研哉 所策劃的全球性展覽，設計出富有創意的狗屋。',
    imageURL: '/assets/projects/afd.png',
    responsibilities: '前端開發',
    websiteURL: 'https://architecturefordogs.com/',
    websiteTitle: 'architecturefordogs.com',
    githubURL: null,
    githubTitle: null,
    articleURL: 'https://www.boring-lab.com/work/afd',
    articleTitle: '文章介紹',
    tags: ['BORING Design', 'Next.js', 'Motion'],
  },
  {
    title: '成功大學單車節 2024 活動網站',
    description: '帶領團隊完成網站架設，並成功吸引超過 10,000 名使用者。',
    imageURL: '/assets/projects/ncku-bike-festival.jpeg',
    responsibilities: 'Tech PM、前端開發',
    websiteURL: 'https://nckubikefestival.ncku.edu.tw/bikeFestival17th-frontend',
    websiteTitle: 'nckubikefestival.ncku.edu.tw',
    githubURL: 'https://github.com/gdsc-ncku/BikeFestival17th-Frontend',
    githubTitle: 'BikeFestival17th-Frontend',
    articleURL: null,
    articleTitle: null,
    tags: ['GDSC NCKU', 'Vue', 'Tailwind CSS'],
  },
  {
    title: 'GDSC NCKU Forum 活動網站',
    description: 'Code to goal, Fuel your soul!',
    imageURL: '/assets/projects/gdsc-ncku-foum.png',
    responsibilities: '前端開發（一人專案）',
    websiteURL: 'https://gdsc-ncku-forum-2024.zeabur.app',
    websiteTitle: 'gdsc-ncku-forum-2024.zeabur.app',
    githubURL: 'https://github.com/gdsc-ncku/gdsc-ncku-forum-2024',
    githubTitle: 'gdsc-ncku-forum-2024',
    articleURL: '/blog/gdsc-journey',
    articleTitle: 'GDSC NCKU 經營心得',
    tags: ['GDSC NCKU', 'Next', 'Tailwind CSS'],
  },
]
